### ISSUE TITLE
a little help needed

### ISSUE THREAD

**Issue by anaraquelmendes** [anaraquelmendes/retina-gallery#1]
Hi Charlie, 

Could you help me in this assignment?
I think I did everything I should to the images.
Thanks, 
Ana

@charlie-quinn

**Comment by charlie-quinn** [comment]
Hey @anaraquelmendes the issue might be with your export process from Photoshop. Let's take a look together in class this week. 👀

**Comment by anaraquelmendes** [comment]
ok, thanks!

________________________________

**Comment by charlie-quinn** [comment]
⚠️`Reminder: please close this issue once it has been resolved.`
